name: MC-Core-Executor
version: 2021.2.1
main: net.verany.executor.CoreExecutor
api-version: 1.16
author: tylix

commands:
  reload:
    aliases: [rl]
  verify:
  afk:
  playtime:
    aliases:
      - pt
  onlinetime:
    aliases:
      - ot
  language:
  credits:
  support:
  globalrank:
    aliases:
      - gr
  chatclear: