name: MC-Core-Executor
version: 2021.4.2
main: net.verany.executor.CoreExecutor
api-version: 1.16
author: tylix

commands:
  reload:
    aliases: [rl]
  verify:
  afk:
  playtime:
    aliases:
      - pt
  onlinetime:
    aliases:
      - ot
  language:
    aliases:
      - sprache
  credits:
  support:
  globalrank:
    aliases:
      - gr
  chatclear:
  removeduplicatekeys:
    aliases:
      - rmdk

depend:
  - CloudNet-Bridge